### ISSUE TITLE
Change task list to no longer be a singleton

### ISSUE THREAD

**Issue by robert-hatfield** [robert-hatfield/one-thing#17]
The task list should not be modified by the Planning VC. Instead, a copy of the list will be passed during segues.
This is necessary because if the user leaves the planning view before it is complete, the selection state of the main task list may be invalid.
The list will only be updated when the user either:
  A. Presses the "Ready to Work" button at the end of review, or
  B. Confirms that they want to keep the tasks they've reviewed so far.

**Changes needed:**
- `TaskList.swift`:
  - [ ] Change `TaskList` class so it is no longer a singleton
- `MainViewController.swift`:
  - [ ] Pass a copy of the list from to `PlanningViewController` on segue
  - [ ] Pass a copy of the list from to `NewTaskViewController` on segue
- `NewTaskViewController.swift`:
  - [ ] Move saving to an appropriate place
- `PlanningViewController.swift`:
  - [ ] Check `if secondIndex >= taskList.allTasks.count` (end of task list reached) when preparing to segue back
  - (Or check `if doneButton.isHidden == false`.)
- [ ] If planning is incomplete when returning to the main VC, ask the user if they want to keep their planning progress.
  - (Maybe show the user how many tasks have not be reviewed.)
- [ ] Update task list and save when returning to main VC if appropriate

**Comment by robert-hatfield** [comment]
- [ ] Change `TaskList` class so it is no longer a singleton
- [ ] Pass a copy of the list from `MainViewController` to `PlanningViewController` on segue
- [ ] Check `if secondIndex >= taskList.allTasks.count` (end of task list reached) when preparing to segue back
  - (Or check `if doneButton.isHidden == false`.)
- [ ] If planning is incomplete when returning to the main VC, ask the user if they want to keep their planning progress.
  - (Maybe show the user how many tasks have not be reviewed.)
- [ ] Update task list and save when returning to main VC if appropriate
